apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: YXN0bGU=              # astle
  POSTGRES_PASSWORD: c3VwZXJzZWNyZXQ=  # supersecret
  POSTGRES_DB: ZXhwZW5zZXM=            # expenses
